---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://106.13.77.83:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
# 设置Kibana界面为中文
i18n.locale: "zh-CN"

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: elk654123
